language: node_js
os:
  - linux
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run test
        - npm run test:coverage
