language: node_js
os:
  - linux
node_js:
  - v15
  - v12
  - v10
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run test
        - npm run test:coverage
