language: node_js

os:
  - linux

node_js:
  - v13
  - v12
  - v11
  - v10
  - v9

jobs:
  include:
    - stage: test
      script:
        - npm install
        - npm run test
        - npm run coveralls
  allow_failures:
    - node_js: v13
